### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by Gaffen**
Pretty self explanatory: adds `bcrypt` and `babel-runtime` to package.json

Needs cross platform testing to confirm that the changes work.

### CODE REVIEW

**Comment by MatejJan** [comment]
Looking at the changed files, only the versions are updated. So the dependencies were already there? Did this help solve the problem anyway? And don't get me wrong, I'm not very experienced with main level dependencies and NPM stuff, so I'm just asking to understand it better.

It works fine for me otherwise, just ran it.

**Comment by Gaffen** [comment]
Yes, I noticed this after committing and pushing. It did fix the error for
me, strange that it didn't find the dependency before I did this though

**Comment by MatejJan** [comment]
I definitely know that another person before you had to install manually these two packages with npm before it would work. So I'll merge this, but also write it in the install file that you might need to manually add them with npm. That'll close the issue report and we'll just revisit all this at one later point.

**Review by MatejJan — APPROVED** [review]
Tested and works.

**Pull request merged**
